### ISSUE TITLE
TreeTagger should not be in this repo

### ISSUE THREAD

**Issue by reckart** [gangeli/ParsingTime#2]
The TreeTagger license unfortunately does not allow redistribution unless you have a written permission from the author. You might want to consider removing it from the repo.

See the license file for tt:

```
...
The licensee has no right to give or sell the system to third
   parties without written permission from the licenser.
...
```

**Comment by gangeli** [comment]
Fair enough. There's no reason for it to be there to begin with, other than the fact that I used it for an experiment.
